stages:
  - validate_and_combine
  - deploy

validate_and_combine_component:
  stage: validate_and_combine
  script:
    - node scripts/json-validator.js component
    - node scripts/combine-jsons.js component
  tags:
    - linux
  only:
    - develop

validate_and_combine_tutorial:
  stage: validate_and_combine
  script:
    - node scripts/json-validator.js tutorial
    - node scripts/combine-jsons.js tutorial
  tags:
    - linux
  only:
    - develop

deploy_to_production:
  stage: deploy
  script:
    - git checkout -b production
    - git add .
    - git commit -m "Automated deployment commit"
    - git push origin production
  tags:
    - linux
  dependencies:
    - validate_and_combine_component
    - validate_and_combine_tutorial
  only:
    - develop
